<?php

namespace AppBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des actualites
     */
    public function findActualiteDESC()
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
                    ->getQuery()->getResult()
        ;
    }

    /**
     * Liste des actualités actives decroissantes
     */
    public function findFindActualiteDescActif($limit, $offset)
    {
        return $this->createQueryBuilder('a')
                    ->where('a.statut = 1')
                    ->orderBy('a.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
