<?php

namespace AppBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Compteur du nombre d'articles actifs
     */
    public function compteur($statut = null)
    {
        if ($statut){
            return $this->listDesc($limit = null, $offset = null)
                        ->select('count(a.id)')
                        ->where('a.statut = 1')
                        ->getQuery()->getSingleScalarResult();
        }else{
            return $this->listDesc($limit = null, $offset = null)
                        ->select('count(a.id)')
                        ->getQuery()->getSingleScalarResult();
        }
    }

    /**
     * Liste des agendas
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listDesc($limit, $offset)->where('a.statut = 1')->getQuery()->getResult();
        } else{
            return $this->listDesc($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * Liste decroissantes des agendas
     */
    public function listDesc($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }
}
