<?php

namespace AppBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des agendas
     */
    public function findAgendaDESC()
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
                    ->getQuery()->getResult()
        ;
    }
}
