<?php

namespace AppBundle\Repository;

/**
 * CommuneRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
