<?php

namespace AppBundle\Repository;

/**
 * CommuneRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des rubriques
     */
    public function findRubriqueDESC()
    {
        return $this->createQueryBuilder('r')
                    ->where('r.statut = 1')
                    ->orderBy('r.id', 'ASC')
        ;
    }

    /**
     * Liste Croissante des rubrique
     */
    public function findRubriqueASC()
    {
        return $this->createQueryBuilder('r')
                    ->orderBy('r.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
