<?php

namespace AppBundle\Repository;

/**
 * ConseillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConseillerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des conseillers par ordre alphabetique
     */
    public function findAllAsc()
    {
        return $this->createQueryBuilder('c')
                    ->orderBy('c.identite', 'ASC')
                    ->getQuery()->getResult();
            ;
    }
}
