<?php

namespace AppBundle\Repository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des dossiers
     */
    public function findAllDesc()
    {
        return $this->createQueryBuilder('d')
                    ->orderBy('d.id', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste decroissante des dossiers actifs
     */
    public function findAllActif($limit,$offset)
    {
        return $this->createQueryBuilder('d')
                    ->where('d.statut = 1')
                    ->orderBy('d.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
