<?php

namespace AppBundle\Repository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des dossiers
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listDesc($limit, $offset)->where('d.statut = 1')->getQuery()->getResult();
        } else{
            return$this->listDesc($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * Liste decroissante des dossiers
     */
    public function listDesc($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('d')
                    ->orderBy('d.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }
}
