<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des informations actives
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listDesc($limit, $offset)->where('i.statut = 1')->getQuery()->getResult();
        }else{
            return $this->listDesc($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * Liste decroissante des informations actives
     */
    public function listDesc($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('i')
                    ->orderBy('i.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }

}
