<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des informations actives
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listDesc($limit, $offset)
                        ->where('i.statut = 1')
                        ->andWhere(':periode BETWEEN i.datedeb AND i.datefin')
                        ->orderBy('i.datefin', 'DESC')
                        ->setParameter('periode', date('Y-m-d', time()))
                        ->getQuery()->getResult()
                ;
        }else{
            return $this->listDesc($limit, $offset)->orderBy('i.datefin', 'DESC')->getQuery()->getResult();
        }
    }

    /**
     * Liste decroissante des informations similaires
     */
    public function findListSimilaire($type, $id, $limit = null, $offset = null)
    {
        return $this->listDesc($limit,$offset)
                    ->where('t.id = :type')
                    ->andWhere('i.statut = 1')
                    ->andWhere('i.id <> :id')
                    ->setParameters([
                        'type' => $type,
                        'id' => $id
                    ])
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste decroissante des informations actives
     */
    public function listDesc($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('i')
                    ->addSelect('t')
                    ->leftJoin('i.typinfo', 't')
                    ->orderBy('i.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }

}
