<?php

namespace AppBundle\Repository;

/**
 * LifestyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LifestyleRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des lifestyle
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listDesc($limit, $offset)->where('l.statut = 1')->getQuery()->getResult();
        }else{
            return $this->listDesc($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * Recherche des lifestyle
     */
    public function listDesc($limit = null, $offset)
    {
        return $this->createQueryBuilder('l')
                    ->addSelect('t')
                    ->leftJoin('l.type', 't')
                    ->orderBy('l.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }
}
