<?php

namespace AppBundle\Repository;

/**
 * LifestyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LifestyleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des articles de lifestyle
     */
    public function findAllDesc()
    {
        return $this->createQueryBuilder('l')
                    ->orderBy('l.id', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     *
     */
    public function findLifestyleActifDesc($limit, $offset)
    {
        return $this->createQueryBuilder('l')
                    ->where('l.statut = 1')
                    ->orderBy('l.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
