<?php

namespace AppBundle\Repository;

/**
 * LifestyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LifestyleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Compteur d'articles
     */
    public function compteur($type = null, $statut = null)
    {
        if ($type && $statut){
            return $this->listDesc()
                        ->select('count(l.id)')
                        ->where('t.slug = :type')
                        ->andWhere('l.statut = 1')
                        ->setParameter('type', $type)
                        ->getQuery()->getResult()
                ;
        }elseif ($statut){
            return $this->listDesc()->select('count(l.id)')->where('l.statut = 1')->getQuery()->getSingleScalarResult();
        }else{
            return $this->listDesc()->select('count(l.id)')->getQuery()->getSingleScalarResult();
        }
    }

    /**
     * Liste des lifestyle
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listDesc($limit, $offset)->where('l.statut = 1')->getQuery()->getResult();
        }else{
            return $this->listDesc($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * liste des lifestyles selon le type
     */
    public function findTypeDesc($type = null, $statut = null, $limit = null, $offset = null)
    {
        if ($type && $statut){
            return $this->listDesc($limit, $offset)
                        ->where('t.slug = :type')
                        ->andWhere('l.statut = 1')
                        ->setParameter('type', $type)
                        ->getQuery()->getResult()
                ;
        }elseif ($type){
            return $this->listDesc($limit, $offset)
                        ->where('t.slug = :type')
                        ->setParameter('type', $type)
                        ->getQuery()->getResult()
                ;
        }else{
            return $this->listDesc($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * Recherche des lifestyle
     */
    public function listDesc($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('l')
                    ->addSelect('t')
                    ->leftJoin('l.type', 't')
                    ->orderBy('l.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }
}
