<?php

namespace AppBundle\Repository;

/**
 * MairieRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MairieRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
