<?php

namespace AppBundle\Repository;

/**
 * MaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaireRepository extends \Doctrine\ORM\EntityRepository
{
}
