<?php

namespace AppBundle\Repository;

/**
 * MunicipaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
