<?php

namespace AppBundle\Repository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des slides
     */
    public function findListDesc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->list($limit, $offset)->where('s.statut = 1')->getQuery()->getResult();
        }else{
            return $this->list($limit, $offset)->getQuery()->getResult();
        }
    }

    /**
     * recherches des slides
     */
    public function list($limit = null, $offset = null)
    {
        return $this->createQueryBuilder('s')
                    ->orderBy('s.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
            ;
    }
}
