<?php

namespace AppBundle\Repository;

/**
 * TypeSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSliderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste croissante des types de sliders
     */
    public function findAllAsc($statut = null, $limit = null, $offset = null)
    {
        if ($statut){
            return $this->listActif()->setFirstResult($offset)->setMaxResults($limit)->getQuery()->getResult()
                ;
        }else{
            return $this->listAll()->setFirstResult($offset)->setMaxResults($limit)->getQuery()->getResult();
        }
    }

    /**
     * fonction de recherche des listes des types actifs
     */
    public function listActif()
    {
        return $this->createQueryBuilder('s')
                    ->where('s.statut = 1')
                    ->orderBy('s.libelle', 'ASC')
            ;
    }

    /**
     * fonction de recherche des listes des types
     */
    public function listAll()
    {
        return $this->createQueryBuilder('s')
                    ->orderBy('s.libelle', 'ASC')
            ;
    }
}
