<?php

namespace AppBundle\Repository;

/**
 * TypeActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des type d'actaulite
     */
    public function findTypeActualiteDESC()
    {
        return $this->createQueryBuilder('t')
                    ->where('t.statut = 1')
                    ->orderBy('t.libelle', 'ASC')
        ;
    }
}
