<?php

namespace AppBundle\Repository;

/**
 * TypeLifestyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLifestyleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste croissante des types de lifestyles
     */
    public function findAllAsc(){
        return $this->createQueryBuilder('l')
                    ->orderBy('l.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste croissante des types de lifestyles actifs
     */
    public function findAllAscActif()
    {
        return $this->createQueryBuilder('l')
                    ->where('l.statut = 1')
                    ->orderBy('l.libelle', 'ASC')
            ;
    }
}
