<?php

namespace AppBundle\Repository;

/**
 * TypeEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des type d'events
     */
    public function findTypeEventDESC()
    {
        return $this->createQueryBuilder('t')
                    ->orderBy('t.libelle', 'DESC')
        ;
    }
}
